# Site settings
title: Sherman Geng
email: sggeng@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Sherman Geng, a Software Architect and Engineer with over 15 years of software development experience
  building great technology solutions for many high profile companies.
permalink: /:categories/:title/
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gengsoft.com" # the base hostname & protocol for your site
url_domain: gengsoft.com
twitter_username: sggeng
github_username:  sggeng
instagram_username: sggeng
linkedin_username: sggeng

# Build settings
markdown: kramdown
